### PR TITLE
Added TEST2 controller

### PR DESCRIPTION
**Pull request by redddot**
Added TEST 2 Controller

### CODE REVIEW

**Review by chetanpopat — CHANGES_REQUESTED** [review]
Please write code in TEST2 controller

**Review by redddot — COMMENTED** [review]
ok, done

**Review by chetanpopat — APPROVED** [review]

**Review by redddot — COMMENTED** [review]
please approve

**Review by chetanpopat — APPROVED** [review]
OK, approved

**Review by chetanpopat — APPROVED** [review]
ok

**Review by chetanpopat — CHANGES_REQUESTED** [review]
okok

**Review by chetanpopat — APPROVED** [review]
reviewed

**Pull request merged**
